In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [6]:
df=pd.read_csv("../data/student_exam_scores.csv")
df.head()

,student_id,hours_studied,sleep_hours,attendance_percent,previous_scores,exam_score
0,S001,8.0,8.8,72.1,45,30.2
1,S002,1.3,8.6,60.7,55,25.0
2,S003,4.0,8.2,73.7,86,35.8
3,S004,3.5,4.8,95.1,66,34.0
4,S005,9.1,6.4,89.8,71,40.3

In [7]:
df.isnull().sum()

student_id            0
hours_studied         0
sleep_hours           0
attendance_percent    0
previous_scores       0
exam_score            0
dtype: int64

In [15]:
X=df.drop(["exam_score", "student_id"], axis=1)
y=df["exam_score"]

In [16]:
X

     hours_studied  sleep_hours  attendance_percent  previous_scores
0              8.0          8.8                72.1               45
1              1.3          8.6                60.7               55
2              4.0          8.2                73.7               86
3              3.5          4.8                95.1               66
4              9.1          6.4                89.8               71
..             ...          ...                 ...              ...
195           10.5          5.4                94.0               87
196            7.1          6.1                85.1               92
197            1.6          6.9                63.8               76
198           12.0          7.3                50.5               58
199           10.2          6.3                97.4               68

[200 rows x 4 columns]

In [17]:
y

0      30.2
1      25.0
2      35.8
3      34.0
4      40.3
       ...
195    42.7
196    40.4
197    28.2
198    42.0
199    37.8
Name: exam_score, Length: 200, dtype: float64

In [18]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [19]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [20]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train_scaled,y_train)
y_pred=model.predict(X_test_scaled)

In [21]:
y_pred

array([28.88607164, 29.68042066, 35.31195586, 31.18044826, 39.44894287,
       41.69158322, 23.96918347, 45.72250896, 41.6529321 , 27.47615681,
       26.09033959, 44.45348162, 27.22577144, 29.33836752, 36.53825172,
       34.75877399, 31.5395367 , 28.52996777, 40.3792585 , 29.84951368,
       21.85245583, 24.08822626, 27.61839558, 27.93331998, 35.96012145,
       43.8081039 , 34.91507705, 28.592239  , 37.57486402, 43.9712545 ,
       27.7683444 , 37.33910217, 37.03824477, 28.28799615, 42.6421297 ,
       21.64648068, 38.42517152, 36.15049022, 44.91531908, 35.47066788])

In [22]:
from sklearn.metrics import mean_squared_error, r2_score

print("MSE:", mean_squared_error(y_test, y_pred))
print("R2:", r2_score(y_test, y_pred))

MSE: 7.761782668623075
R2: 0.8537447137159516

In [24]:
model.coef_

array([4.89795269, 1.29206941, 1.52962586, 2.83074878])

In [25]:
model.intercept_

np.float64(33.85125000000001)